import type { Metadata } from "next";
import { DynaPuff, Vazirmatn } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header/Header";

const vazirMatn = Vazirmatn({
  variable: "--font-vazir-matn",
  subsets: ["arabic", "latin"],
  weight: ["400", "700", "900"],
});

const dynaPuff = DynaPuff({
  variable: "--font-dyna-puff",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${vazirMatn.variable} ${dynaPuff.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="w-full sticky top-0 z-100">
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
