import { Listing } from "@/types/dataTypes";

export const listings: Listing[] = [
  {
    id: "listing-001",
    brand: "Toyota",
    model: "Camry",
    trim: "XLE 2.5L",
    year: 2026,
    color: "Pearl White",
    colorHex: "#F5F5F0",
    engine: "2.5L 4-Cyl Hybrid",
    transmission: "CVT Automatic",
    fuelType: "Hybrid",
    bodyType: "Sedan",
    city: "Tehran",
    deliveryDays: 3,
    sellerName: "Aria Motors",
    sellerVerified: true,
    sellerResponseRate: 97,
    sellerMemberSince: "2021",
    sellerActiveListings: 14,
    sellerAvatar: "AM",
    price: 2850000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-18",
    factoryOptions: [
      "Sunroof",
      "Leather Seats",
      "JBL Audio",
      "Blind Spot Monitor",
      "Wireless Charging",
    ],
    marketAvgBuy: 2780000000,
    marketAvgSell: 2920000000,
    priceVsMarket: 2.5,
    trend7d: 1.8,
  },
  {
    id: "listing-002",
    brand: "Hyundai",
    model: "Tucson",
    trim: "N-Line AWD",
    year: 2026,
    color: "Midnight Black",
    colorHex: "#1A1A1A",
    engine: "2.0L Turbo",
    transmission: "8-Speed DCT",
    fuelType: "Petrol",
    bodyType: "SUV",
    city: "Isfahan",
    deliveryDays: 7,
    sellerName: "Parsian Auto",
    sellerVerified: true,
    sellerResponseRate: 91,
    sellerMemberSince: "2022",
    sellerActiveListings: 8,
    sellerAvatar: "PA",
    price: 3200000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-17",
    factoryOptions: [
      "Panoramic Roof",
      "Ventilated Seats",
      "Bose Audio",
      "HUD",
      "Smart Parking",
    ],
    marketAvgBuy: 3100000000,
    marketAvgSell: 3350000000,
    priceVsMarket: -4.5,
    trend7d: 2.1,
  },
  {
    id: "listing-003",
    brand: "Kia",
    model: "Sportage",
    trim: "GT-Line 1.6T",
    year: 2025,
    color: "Steel Gray",
    colorHex: "#8A9BAE",
    engine: "1.6L Turbo GDI",
    transmission: "7-Speed DCT",
    fuelType: "Petrol",
    bodyType: "SUV",
    city: "Mashhad",
    deliveryDays: 14,
    sellerName: "Mehr Khodro",
    sellerVerified: false,
    sellerResponseRate: 78,
    sellerMemberSince: "2023",
    sellerActiveListings: 3,
    sellerAvatar: "MK",
    price: 2650000000,
    priceUnit: "Toman",
    status: "pending",
    listedDate: "2026-05-15",
    factoryOptions: ["Sunroof", "Heated Seats", "CarPlay", "Lane Assist"],
    marketAvgBuy: 2580000000,
    marketAvgSell: 2720000000,
    priceVsMarket: 0.8,
    trend7d: -0.5,
  },
  {
    id: "listing-004",
    brand: "BMW",
    model: "3 Series",
    trim: "330i M Sport",
    year: 2026,
    color: "Alpine White",
    colorHex: "#F0EFE8",
    engine: "2.0L TwinPower Turbo",
    transmission: "8-Speed Steptronic",
    fuelType: "Petrol",
    bodyType: "Sedan",
    city: "Tehran",
    deliveryDays: 21,
    sellerName: "Bavarian Motors TH",
    sellerVerified: true,
    sellerResponseRate: 99,
    sellerMemberSince: "2019",
    sellerActiveListings: 22,
    sellerAvatar: "BM",
    price: 7800000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-19",
    factoryOptions: [
      "M Sport Package",
      "Harman Kardon",
      "Adaptive Cruise",
      "Parking Assistant Plus",
      "Live Cockpit Pro",
    ],
    marketAvgBuy: 7600000000,
    marketAvgSell: 8100000000,
    priceVsMarket: -3.7,
    trend7d: 3.2,
  },
  {
    id: "listing-005",
    brand: "Geely",
    model: "Coolray",
    trim: "Premium Plus",
    year: 2026,
    color: "Ocean Blue",
    colorHex: "#1A6B9A",
    engine: "1.5L Turbo",
    transmission: "7-Speed DCT",
    fuelType: "Petrol",
    bodyType: "SUV",
    city: "Shiraz",
    deliveryDays: 5,
    sellerName: "Star Auto Group",
    sellerVerified: true,
    sellerResponseRate: 88,
    sellerMemberSince: "2022",
    sellerActiveListings: 11,
    sellerAvatar: "SA",
    price: 1450000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-16",
    factoryOptions: [
      "360 Camera",
      "Panoramic Roof",
      "Wireless CarPlay",
      "LED Matrix",
    ],
    marketAvgBuy: 1380000000,
    marketAvgSell: 1520000000,
    priceVsMarket: 1.4,
    trend7d: 0.9,
  },
  {
    id: "listing-006",
    brand: "Haval",
    model: "H6",
    trim: "Ultra HEV",
    year: 2026,
    color: "Crimson Red",
    colorHex: "#B91C1C",
    engine: "1.5L PHEV",
    transmission: "7-Speed DCT",
    fuelType: "Plug-in Hybrid",
    bodyType: "SUV",
    city: "Tabriz",
    deliveryDays: 10,
    sellerName: "Haval Center NW",
    sellerVerified: true,
    sellerResponseRate: 94,
    sellerMemberSince: "2020",
    sellerActiveListings: 7,
    sellerAvatar: "HC",
    price: 2100000000,
    priceUnit: "Toman",
    status: "negotiable",
    listedDate: "2026-05-14",
    factoryOptions: [
      "Sunroof",
      "Heated & Ventilated Seats",
      "Meridian Audio",
      "PHEV Charging Cable",
    ],
    marketAvgBuy: 2050000000,
    marketAvgSell: 2180000000,
    priceVsMarket: -2.3,
    trend7d: 1.1,
  },
  {
    id: "listing-007",
    brand: "Jetour",
    model: "X70 Plus",
    trim: "Executive",
    year: 2025,
    color: "Champagne Gold",
    colorHex: "#C9A96E",
    engine: "2.0L Turbo",
    transmission: "6-Speed AT",
    fuelType: "Petrol",
    bodyType: "SUV",
    city: "Tehran",
    deliveryDays: 2,
    sellerName: "Capital Auto TH",
    sellerVerified: true,
    sellerResponseRate: 85,
    sellerMemberSince: "2023",
    sellerActiveListings: 6,
    sellerAvatar: "CA",
    price: 1780000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-19",
    factoryOptions: [
      "Panoramic Roof",
      "Leather Seats",
      '10.1" Infotainment',
      "TPMS",
    ],
    marketAvgBuy: 1720000000,
    marketAvgSell: 1850000000,
    priceVsMarket: 0.6,
    trend7d: -1.2,
  },
  {
    id: "listing-008",
    brand: "Chery",
    model: "Tiggo 8 Pro",
    trim: "Max AWD",
    year: 2026,
    color: "Glacier White",
    colorHex: "#EAECEE",
    engine: "2.0T TGDI",
    transmission: "7-Speed DCT",
    fuelType: "Petrol",
    bodyType: "SUV",
    city: "Karaj",
    deliveryDays: 8,
    sellerName: "Sina Motors",
    sellerVerified: false,
    sellerResponseRate: 72,
    sellerMemberSince: "2024",
    sellerActiveListings: 2,
    sellerAvatar: "SM",
    price: 2350000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-13",
    factoryOptions: [
      "7-Seat Configuration",
      "Panoramic Roof",
      "BOSE Audio",
      "Wireless Charging",
    ],
    marketAvgBuy: 2280000000,
    marketAvgSell: 2440000000,
    priceVsMarket: -1.7,
    trend7d: 0.4,
  },
  {
    id: "listing-009",
    brand: "MVM",
    model: "550",
    trim: "Sport Plus",
    year: 2025,
    color: "Deep Blue",
    colorHex: "#1E3A5F",
    engine: "1.5L Naturally Aspirated",
    transmission: "5-Speed Manual",
    fuelType: "Petrol",
    bodyType: "Sedan",
    city: "Tehran",
    deliveryDays: 1,
    sellerName: "Tehran Auto Mall",
    sellerVerified: true,
    sellerResponseRate: 96,
    sellerMemberSince: "2020",
    sellerActiveListings: 19,
    sellerAvatar: "TA",
    price: 680000000,
    priceUnit: "Toman",
    status: "reserved",
    listedDate: "2026-05-12",
    factoryOptions: ["CarPlay", "Rear Camera", "ABS + EBD", "Alloy Wheels"],
    marketAvgBuy: 650000000,
    marketAvgSell: 710000000,
    priceVsMarket: 3.1,
    trend7d: -2.1,
  },
  {
    id: "listing-010",
    brand: "Honda",
    model: "CR-V",
    trim: "Touring Hybrid",
    year: 2026,
    color: "Sonic Gray Pearl",
    colorHex: "#9CA3AF",
    engine: "2.0L i-MMD Hybrid",
    transmission: "e-CVT",
    fuelType: "Hybrid",
    bodyType: "SUV",
    city: "Tehran",
    deliveryDays: 30,
    sellerName: "Aria Motors",
    sellerVerified: true,
    sellerResponseRate: 97,
    sellerMemberSince: "2021",
    sellerActiveListings: 14,
    sellerAvatar: "AM",
    price: 5200000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-19",
    factoryOptions: [
      "Honda Sensing Suite",
      "Bose Premium Audio",
      "Power Tailgate",
      "Heated Front & Rear Seats",
    ],
    marketAvgBuy: 5050000000,
    marketAvgSell: 5380000000,
    priceVsMarket: -1.9,
    trend7d: 2.7,
  },
  {
    id: "listing-011",
    brand: "IKCO",
    model: "Dena Plus",
    trim: "Turbo ELX",
    year: 2026,
    color: "Silver Metallic",
    colorHex: "#C0C0C0",
    engine: "1.65T Turbo",
    transmission: "6-Speed AT",
    fuelType: "Petrol",
    bodyType: "Sedan",
    city: "Tehran",
    deliveryDays: 0,
    sellerName: "IKCO Direct",
    sellerVerified: true,
    sellerResponseRate: 99,
    sellerMemberSince: "2018",
    sellerActiveListings: 45,
    sellerAvatar: "ID",
    price: 890000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-19",
    factoryOptions: [
      "Factory Warranty 3yr",
      "CarPlay",
      "Reverse Camera",
      "Cruise Control",
    ],
    marketAvgBuy: 860000000,
    marketAvgSell: 930000000,
    priceVsMarket: 1.1,
    trend7d: 0.3,
  },
  {
    id: "listing-012",
    brand: "Volkswagen",
    model: "Tiguan",
    trim: "R-Line 2.0T",
    year: 2026,
    color: "Deep Black Pearl",
    colorHex: "#0D0D0D",
    engine: "2.0L TSI",
    transmission: "7-Speed DSG",
    fuelType: "Petrol",
    bodyType: "SUV",
    city: "Tehran",
    deliveryDays: 45,
    sellerName: "Euro Motors Tehran",
    sellerVerified: true,
    sellerResponseRate: 93,
    sellerMemberSince: "2020",
    sellerActiveListings: 9,
    sellerAvatar: "EM",
    price: 6100000000,
    priceUnit: "Toman",
    status: "active",
    listedDate: "2026-05-11",
    factoryOptions: [
      "Digital Cockpit Pro",
      "IQ.Drive",
      "Panoramic Roof",
      "Harman Kardon",
      "Keyless Entry",
    ],
    marketAvgBuy: 5950000000,
    marketAvgSell: 6350000000,
    priceVsMarket: -4.0,
    trend7d: 1.5,
  },
];

export const priceChartData = [
  { date: "May 13", camry: 2780, tucson: 3120, sportage: 2640 },
  { date: "May 14", camry: 2800, tucson: 3145, sportage: 2630 },
  { date: "May 15", camry: 2820, tucson: 3160, sportage: 2620 },
  { date: "May 16", camry: 2810, tucson: 3190, sportage: 2655 },
  { date: "May 17", camry: 2835, tucson: 3175, sportage: 2648 },
  { date: "May 18", camry: 2848, tucson: 3198, sportage: 2643 },
  { date: "May 19", camry: 2850, tucson: 3200, sportage: 2650 },
];

export const brandVolumeData = [
  { brand: "Toyota", listings: 38 },
  { brand: "Hyundai", listings: 34 },
  { brand: "Kia", listings: 29 },
  { brand: "IKCO", listings: 52 },
  { brand: "Geely", listings: 27 },
  { brand: "Haval", listings: 21 },
  { brand: "BMW", listings: 15 },
  { brand: "Jetour", listings: 18 },
];

export function formatPrice(price: number): string {
  if (price >= 1000000000) {
    return (price / 1000000000).toFixed(2) + "B";
  }
  if (price >= 1000000) {
    return (price / 1000000).toFixed(0) + "M";
  }
  return price.toLocaleString();
}
