export const sellers = [
  {
    id: "seller-aria",
    name: "آریا موتورز",
    city: "تهران",
    listings: 14,
    responseRate: 97,
    since: "۱۴۰۰",
    initials: "آم",
    color: "#1B4FD8",
    specialty: "تویوتا · هوندا · هیبریدی",
  },
  {
    id: "seller-bavarian",
    name: "باواریان موتورز",
    city: "تهران",
    listings: 22,
    responseRate: 99,
    since: "۱۳۹۸",
    initials: "بم",
    color: "#0066B1",
    specialty: "بی‌ام‌و · آئودی · مرسدس",
  },
  {
    id: "seller-parsian",
    name: "پارسیان اتو",
    city: "اصفهان",
    listings: 8,
    responseRate: 91,
    since: "۱۴۰۱",
    initials: "پا",
    color: "#002C5F",
    specialty: "هیوندای · کیا · جیلی",
  },
  {
    id: "seller-tehranmall",
    name: "تهران اتو مال",
    city: "تهران",
    listings: 19,
    responseRate: 96,
    since: "۱۳۹۹",
    initials: "تا",
    color: "#374151",
    specialty: "داخلی · محدوده بودجه",
  },
];
